export const flavorText = {
  introText: ["that's all folks!", "hey, mind letting us know who you are?"],
  firstTimeText: [
    "first\ntimer",
    "nice to meet you,<br /> let's be best friends!",
    "hey, a smile is a great start",
    "cool to see you here!<br />  we've been waiting for you!",
    "winterfell is yours, your grace.",
    "and another one",
    "we like you already",
    "hi, I'm a button!",
    "I knew you would show up!",
    "welcome handsome ;)",
    "this is the beginning of<br />  something awesome",
    "whats up, yo?",
    "We've been waiting for you! Welcome!",
    "want a cup of joe? ☕",
    "may The Force be with you.",
    "we keep it casual around here.<br />  So roll up your sleeves pls",
    "I'm gonna make you mine 😉"
  ],
  regularText: [
    "regular\nvisitor",
    "great to see you again,<br /> have a good one!",
    "please leave your coat in the cloak room",
    "enjoy your day<br /> and stay happy & relaxed!",
    "thought I recognized that fingertip! ❤️",
    "you know what to do",
    "keep moving on",
    "great weather, right?",
    "we missed you.",
    "life is better with you in it",
    "where have you been all my life",
    "I'm a button. you're a person.<br />  perfect match!",
    "oh! how you doin' 😏",
    "Nice to see you again!",
    "👊*bumping hand*<br /> 💥*making explosion sound*",
    "I thought I saw that fingerprint before! Welcome!",
    "I knew I saw that face before! Welcome!",
    "omg, where have you been the whole time?"
  ],
  footerFirstText: [
    "you look great today by the way!",
    "confused? just grab one of our guys.\nFYI, they can't run",
    "feel free to take a cup of coffee or tea",
    "lost? no worries, we're here for you.\n just ask for help",
    'kiitos ("Take your shoes off" in Finnish)',
    "people like you make this place awesome",
    "if i had a cookie I'd give you half",
    "do you always look this good?",
    "mirror mirror in the hall,\n  meet our beauties on the wall",
    "you brought the sauce, awesome sauce",
    "there's ordinary,\n  and then there's you.",
    "I like your look! ",
    "grab yourself a seat\n  and mingle in",
    "remember, your focus determines your reality",
    "you deserve our secret gift for coming.\n  Go look for it.",
    "you're the one for me. you're my ecstasy.\n  you're the one I needddd"
  ],
  footerRegularText: [
    "stay fancy, my friend",
    "stay awesome, handsome!",
    "remember to use our job wall",
    "having you on the team makes a huge difference",
    "you are better than unicorns and sparkles combined",
    "your smile is awesome, keep it always",
    "what a great smile!",
    "you know, right?",
    "no need to read this message",
    "your presence is a candle in the darkness",
    "gosh, it's good to see you again",
    "I would totally invite you to my dinner party",
    "back again? we would almost think you have a crush on us ;)",
    "if I had arms I'd give you a hug",
    "love your groovy style",
    "good hair day I see there :D",
    "That color suits you! 😉",
    "you're looking so fine today",
    "keep pushing yourself like you pushed my button",
    "I like how you pushed my button",
    "just say hi and smile to everyone,\n come in and feel yourself at home"
  ],
  footerText: [
    "you look great today by the way!",
    "confused? just grab one of our guys.\nFYI, they can't run",
    "feel free to take a cup of coffee or tea",
    "lost? no worries, we're here for you.\n just ask for help",
    'kiitos ("Take your shoes off" in Finnish)',
    "people like you make this place awesome",
    "if i had a cookie I'd give you half",
    "do you always look this good?",
    "mirror mirror in the hall,\n  meet our beauties on the wall",
    "you brought the sauce, awesome sauce",
    "there's ordinary,\n  and then there's you.",
    "I like your look! ",
    "grab yourself a seat\n  and mingle in",
    "remember, your focus determines your reality",
    "you deserve our secret gift for coming.\n  Go look for it.",
    "you're the one for me. you're my ecstasy.\n  you're the one I needddd",
    "stay fancy, my friend",
    "stay awesome, handsome!",
    "remember to use our job wall",
    "having you on the team makes a huge difference",
    "you are better than unicorns and sparkles combined",
    "your smile is awesome, keep it always",
    "what a great smile!",
    "you know, right?",
    "no need to read this message",
    "your presence is a candle in the darkness",
    "gosh, it's good to see you again",
    "I would totally invite you to my dinner party",
    "back again? we would almost think you have a crush on us ;)",
    "if I had arms I'd give you a hug",
    "love your groovy style",
    "good hair day I see there :D",
    "That color suits you! 😉",
    "you're looking so fine today",
    "keep pushing yourself like you pushed my button",
    "I like how you pushed my button",
    "just say hi and smile to everyone,\n come in and feel yourself at home"
  ]
};
